No error message after running this command:

pyshacl -s catalog.ttl -m -i rdfs -a -j -f human test.ttl

# Output


Validation Report
Conforms: True


